version: '3'

services:
  sidecar:
    build:
      dockerfile: dockerfiles/sidecar.dockerfile
      context: ..
      args:
        - INSTALL_DEV=true
    command: 
      - "--"
      - "sh"
      - "./scripts/start.sh"
    ports:
      - "8889:80"
    env_file:
      - ../env/.env
    
    networks:
      - springhead-network
      - function-network
    
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13.7
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - ../env/.env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"

    networks:
      - springhead-network
      - function-network
  
networks:
  springhead-network:
  
  function-network:
      
